coverage:
    range: 70..100
    round: down
    status:
        project:
            default:
                target: 100%
        patch:
            default:
                target: 100%
ignore:  
    - "src/index.tsx"
    - "src/helpers/globalVariables.ts"