export interface Suspect {
    id : number,
    title: string,
    dateOfBirth: string,
    hair: string,
    eyes: string,
    height: number,
    weight: string,
    sex: string,
    race: string,
    nationality: string,
    scarsAndMarks: string,
    rewardText: string,
    caution: string,
    details: string,
    warningMessage: string,
    fbiUid: string,
    modified: string,
    publication: string,
}
